version: "3"
services:
  app:
    container_name: server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME: root
      - MONGO_INITDB_ROOT_PASSWORD: example
      - MONGODB_DATABASE=hackathon
      - ALLOW_EMPTY_PASSWORD=yes
