version: "3"
services:
  app:
    container_name: server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
      image: mongo
      container_name: mongodb
      hostname: mongodb
      environment:
          - MONGODB_USER="user"
          - MONGODB_PASS="pass"
          - MONGO_INITDB_DATABASE="hackathon"
      ports:
          - "27017:27017"
