version: "3"
services:
  app:
    container_name: server
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongodb
  mongodb:
      image: mongo:3.2
      container_name: mongodb
      hostname: mongodb
      environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=hackathon
      volumes:
        - ./data/db:/data/db
      ports:
          - 27017:27017
